### ISSUE TITLE
Reading full ukblc05.xls files in 10_dx_interest_rate_swaps

### ISSUE THREAD

**Issue by finmod** [yhilpisch/dx#3]
Hello Yves,

The data sheets oisf, fwds in the BoE yield curve files ukois09.xls and ukblc05.xls are an intermediate stage added to the original file to transpose the original matrices of data. This works well as a demo for a small matrix but becomes impossible when the full historical data of ukois09_mdaily.xls are downloaded (e.g. 2750Rx61C cannot be transposed in Excel).

Question: what do you advise doing on data input from these BoE Excel files into pandas?  There must be a way to read/transpose directly from the original .xls files into the right data frame in python.

Thank you.

**Comment by yhilpisch** [comment]
It should be possible to read the data into a DataFrame object and then
swapping index and columns.

On 12 January 2016 at 03:30, finmod notifications@github.com wrote:

> Hello Yves,
> 
> The data sheets oisf, fwds in the BoE yield curve files ukois09xls and
> ukblc05xls are an intermediate stage added to the original file to
> transpose the original matrices of data This works well as a demo for a
> small matrix but becomes impossible when the full historical data of
> ukois09_mdailyxls are downloaded (eg 2750Rx61C cannot be transposed in
> Excel)
> 
> Question: what do you advise doing on data input from these BoE Excel
> files into pandas? There must be a way to read/transpose directly from the
> original xls files into the right data frame in python
> 
> Thank you
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/yhilpisch/dx/issues/3.

## 

Dr. Yves J. Hilpisch

The Python Quants GmbH

http://datapark.io
http://tpq.io | http://pqp.io
http://fpq.io | http://pfc.tpq.io
