### ISSUE TITLE
single_risk.py, max_value, mean_value, min_value

### ISSUE THREAD

**Issue by vcleung** [yhilpisch/dx#8]
# average value over whole path
        mean_value = np.mean(paths[:time_index], axis=1)
        # maximum value over whole path
        max_value = np.amax(paths[:time_index], axis=1)[-1]
        # minimum value over whole path
        min_value = np.amin(paths[:time_index], axis=1)[-1]

Should be:
        # average value over whole path
        mean_value = np.mean(paths[:time_index], axis=0)
        # maximum value over whole path
        max_value = np.amax(paths[:time_index], axis=0)
        # minimum value over whole path
        min_value = np.amin(paths[:time_index], axis=0)

**Comment by yhilpisch** [comment]
Thanks for pointing this out.

Have corrected the code, committed and pushed the changes.
